<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CMDLHRLT104" name="tests.MyScripts" tests="4" failures="1" timestamp="10 Oct 2017 11:25:35 GMT" time="216.956" errors="0">
  <testcase name="ReferralSource" time="41.511" classname="tests.MyScripts">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Number is not enetered according to pattern in Home Phone field expected [(543) 534-5345   5435345345] but found [(543) 534-5345],
	Number is not enetered according to pattern in Mobile Phone field expected [(453) 453-4534   4534534534] but found [(453) 453-4534],
	Number is not enetered according to pattern in Office Phone field expected [(234) 234-2342 Ext 3423   23423423423423] but found [(234) 234-2342 Ext 3423]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Number is not enetered according to pattern in Home Phone field expected [(543) 534-5345   5435345345] but found [(543) 534-5345],
	Number is not enetered according to pattern in Mobile Phone field expected [(453) 453-4534   4534534534] but found [(453) 453-4534],
	Number is not enetered according to pattern in Office Phone field expected [(234) 234-2342 Ext 3423   23423423423423] but found [(234) 234-2342 Ext 3423]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at tests.MyScripts.ReferralSource(MyScripts.java:510)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- ReferralSource -->
  <testcase name="Opening_browser" time="11.032" classname="tests.MyScripts"/>
  <testcase name="PrefferedLanguage" time="119.343" classname="tests.MyScripts"/>
  <testcase name="login" time="45.070" classname="tests.MyScripts"/>
</testsuite> <!-- tests.MyScripts -->
